output: web
highlighter:         pygments
permalink:           pretty
# relative_permalinks: true


collections:
  test:
    output: false           # true - в браузере доступен  /_test/index.html  
    permalink: /_test/:title.md
