

output: web


theme: jekyll-theme-primer

github:
  source:
    branch: "primer"
    path: "/"




# подключим подкаталог            но можно использовать _posts  - подкаталог по-умолчанию
collections:
  test:
    output: true           # false - 404 для всех файлов.       при true - в браузере доступен  /_test/index.html  
    permalink: /_test/:title.md

