output: web
highlighter:         pygments
permalink:           pretty
# relative_permalinks: true


collections:
  test:
    output: true           # false - 404 для всех файлов.       при true - в браузере доступен  /_test/index.html  
    permalink: /_test/:title.md
