output: web


# highlighter:         pygments
#highlighter: pygments       # rouge
#markdown:   redcarpet 
# highlighter: pygments 
# redcarpet: extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]


#markdown: redcarpet
#highlighter: pygments



permalink:           pretty
# relative_permalinks: true        -- GitHub Pages and Jekyll no longer support relative permalinks.


# подключим подкаталог            но можно использовать _posts  - подкаталог по-умолчанию
collections:
  test:
    output: true           # false - 404 для всех файлов.       при true - в браузере доступен  /_test/index.html  
    permalink: /_test/:title.md
